name = "WildLight"
author = "Alfakynz"
version = "4.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36cfb7e205708128101a907b81c2382570c56231d3c897ad665cb5c06b36b660"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
