name = "WildLight"
author = "Alfakynz"
version = "4.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ce6ea8f1252ad55c43b7fcf0a3954380a2d14b77837a5892f0f86e162e590e9"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
