name = "WildLight"
author = "Alfakynz"
version = "3.9.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c4121db7406efa354426dcd8b18ab8568d4fd178ccfd2c2579ff7c61ab0f437"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
