name = "WildLight"
author = "Alfakynz"
version = "3.9.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b6563b3e020471dc82e6bf8b33d1dfeff290b303d547ecd9f2ed0051ad40832a"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
