name = "WildLight"
author = "Alfakynz"
version = "4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "718e13dd48e1872b6a6825f35017e423c5b7bf3fa8eae536a94b5001ea9d440c"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
