name = "WildLight"
author = "Alfakynz"
version = "4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "250a43f73f9ccf6a9d92b758889c9e261cff6d2718fc6cc631645a10293eca99"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
