name = "WildLight"
author = "Alfakynz"
version = "3.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b44691fb77a6be64a2092798b5a9916c2001a164364ae3625136f7a463ced682"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
