name = "WildLight"
author = "Alfakynz"
version = "4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8ee2248ac620ec51f1873825c434e6061476b938addaa2ea59f36ba0a8258db"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
