name = "WildLight"
author = "Alfakynz"
version = "3.9.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3523d0a0c58a01219144d648862172757b7496c4ac81a303d61de3853b1bf641"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
