name = "WildLight"
author = "Alfakynz"
version = "3.7.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "258be6427e855e00e0c06db7ad53476968cbe5f083ba58388d034910ca45c8fe"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
