name = "WildLight"
author = "Alfakynz"
version = "4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "777afa08aa45d040f2375daa14343b5b9d2376e2e284ac3cc186d14fed4cfcaf"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
