name = "WildLight"
author = "Alfakynz"
version = "3.9.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eea4c27d4f811fcb95250ca46fb70ea8bd754cd4893f7b5c792f65aa1fc3f08e"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
