name = "WildLight"
author = "Alfakynz"
version = "3.7.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42ba1554af9288a669a683203531cb0fe89ee18415691c755c6e32a417d9ae09"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
