name = "WildLight"
author = "Alfakynz"
version = "4.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49bcba5e166c58ba10eca5a21b013dd2666969db83b135d5f83a217aab74ccdd"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
