name = "WildLight"
author = "Alfakynz"
version = "4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b3b1e97aa63a86eeb1e6930b3287f1f2b1c0313fe156c3c51cd7d5a7abea4e6f"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
