name = "WildLight"
author = "Alfakynz"
version = "3.9.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7fcef81b9d5c5ee569fce8004370ba7f9bef464e9da5b1646b2af8d019df80e4"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
