name = "WildLight"
author = "Alfakynz"
version = "3.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b960ad9968609bcce12544d85b004cf80f4c00a29c5586297154ceb820ff3a30"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
