name = "WildLight"
author = "Alfakynz"
version = "3.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "535369eb95be2f02381683e426ff4915d65ebc9ed99f9ed7d2dafb3932d58823"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
