name = "WildLight"
author = "Alfakynz"
version = "3.9.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e58579ca69714efbeb6f0fe3ed33576dcb102e034ec3f1129828c32d0272a3b3"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
