name = "WildLight"
author = "Alfakynz"
version = "3.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e019a3f8a7b41442828c504ddf3794a47b1f4dc0a7065e049c7e4ec2d5d689f"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
