name = "WildLight"
author = "Alfakynz"
version = "3.7.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9dd36e9cc7ba96f1c026be95527190ffae27e2afcdf3574aa4efd547f1766e07"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
