name = "WildLight"
author = "Alfakynz"
version = "3.7.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d7e7b86bfdcbf62212cf45828c7174dc771dab6d16ac81ebd57ce392ecb39aa"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
