name = "WildLight"
author = "Alfakynz"
version = "3.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f960fbcb10f4b7cc4613c6d637520dcbf6c9d3a7a9108ab8c650cbf82733ea4f"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
